-- Rollback-only hosted channel smoke assertions. Run only while demo tables are empty.
begin;
set local statement_timeout='90s';
set local lock_timeout='5s';
lock table public.restaurants,public.restaurant_memberships,public.orders,private.menus,private.menu_versions,private.guest_sessions,private.ai_usage_windows,private.idempotency_requests,private.outbox_events,private.staff_ai_usage,private.voice_sessions,private.channel_order_receipts,private.messaging_conversations,private.messaging_updates,private.messaging_replies in share row exclusive mode;
create temporary table channel_checks(ok boolean not null);
create function pg_temp.channel_assert(p_ok boolean) returns void language plpgsql as $$begin if p_ok is not true then raise exception 'CHANNEL_ASSERTION_FAILED';end if;insert into pg_temp.channel_checks values(true);end;$$;
do $tests$
declare actor uuid:='a0000000-0000-4000-8000-000000000001'; restaurant uuid:='b0000000-0000-4000-8000-000000000001'; v jsonb; r jsonb; c jsonb; pending jsonb; q jsonb; t jsonb; menu jsonb; cart jsonb; n integer;
begin
 if exists(select 1 from public.restaurants) or exists(select 1 from public.orders) or exists(select 1 from private.voice_sessions) or exists(select 1 from private.messaging_conversations) or exists(select 1 from private.staff_ai_usage)
 or exists(select 1 from auth.users where id=actor) then raise exception 'NONEMPTY_FIXTURE_TARGET';end if;
 insert into auth.users(id,email) values(actor,'channel-test@example.invalid');
 insert into public.restaurants(id,name,slug) values(restaurant,'Channel test','channel-test');
 insert into public.restaurant_memberships(restaurant_id,user_id,role) values(restaurant,actor,'owner');
 menu:='{"id":"c0000000-0000-4000-8000-000000000001","restaurantId":"b0000000-0000-4000-8000-000000000001","version":1,"currency":"SGD","name":"Test","dishes":[{"id":"d0000000-0000-4000-8000-000000000001","name":"Soup","priceCents":600,"available":true,"modifierGroups":[]}]}';
 cart:='{"restaurantId":"b0000000-0000-4000-8000-000000000001","menuId":"c0000000-0000-4000-8000-000000000001","menuVersion":1,"lines":[{"dishId":"d0000000-0000-4000-8000-000000000001","quantity":1,"optionIds":[]}]}';
 perform public.publish_menu(restaurant,actor,menu);
 for n in 1..20 loop perform public.consume_staff_ai_budget(actor,restaurant,'extraction');end loop;
 begin perform public.consume_staff_ai_budget(actor,restaurant,'extraction');raise exception 'EXPECTED_RATE_LIMIT';exception when raise_exception then if sqlerrm<>'RATE_LIMITED' then raise;end if;end;
 perform pg_temp.channel_assert(true);
 perform pg_temp.channel_assert(public.consume_staff_ai_budget(actor,restaurant,'voice')=restaurant);
 v:=public.create_voice_session(actor,restaurant,'hosted-channel-test');
 perform pg_temp.channel_assert(v->>'status'='active');
 r:=public.begin_voice_review(actor,(v->>'id')::uuid);
 r:=public.begin_voice_review(actor,(v->>'id')::uuid);
 begin perform public.save_voice_review(actor,(v->>'id')::uuid,cart,1);raise exception 'EXPECTED_STALE';exception when raise_exception then if sqlerrm<>'STALE_REVIEW' then raise;end if;end;
 perform pg_temp.channel_assert(true);
 r:=public.save_voice_review(actor,(v->>'id')::uuid,cart,2);
 perform pg_temp.channel_assert((r->'quote'->>'totalCents')::integer=600);
 t:=public.submit_voice_order(actor,(v->>'id')::uuid,(r->>'confirmationNonce')::uuid);
 perform pg_temp.channel_assert(t->>'source'='voice' and t->>'paymentStatus'='unpaid');
 perform public.close_voice_session(actor,(v->>'id')::uuid);
 perform pg_temp.channel_assert(public.submit_voice_order(actor,(v->>'id')::uuid,(r->>'confirmationNonce')::uuid)=t);
 c:=public.messaging_claim_update('telegram','testbot',restaurant,'recipient','1',repeat('4',64));
 perform pg_temp.channel_assert(c->>'status'='claimed');
 perform pg_temp.channel_assert(public.messaging_claim_update('telegram','testbot',restaurant,'recipient','1',repeat('4',64))->>'status'='busy');
 q:=public.quote_cart(c->>'sessionTokenHash',cart);
 pending:=jsonb_build_object('cart',cart,'quote',q,'confirmationNonce','e0000000-0000-4000-8000-000000000001','idempotencyKey','f0000000-0000-4000-8000-000000000001');
 perform public.messaging_complete_update((c->>'conversationId')::uuid,(c->>'leaseId')::uuid,'1',jsonb_build_object('version',1,'pending',pending,'lastTicket',null),jsonb_build_object('text','Review','confirmationNonce','e0000000-0000-4000-8000-000000000001'));
 perform pg_temp.channel_assert(public.messaging_claim_update('telegram','testbot',restaurant,'recipient','1',repeat('4',64))->>'status'='duplicate');
 c:=public.messaging_claim_update('telegram','testbot',restaurant,'recipient','2',repeat('4',64));
 t:=public.messaging_submit_order((c->>'conversationId')::uuid,(c->>'leaseId')::uuid,'2','e0000000-0000-4000-8000-000000000001');
 perform pg_temp.channel_assert(t->>'source'='telegram');
 perform pg_temp.channel_assert(public.messaging_submit_order((c->>'conversationId')::uuid,(c->>'leaseId')::uuid,'2','e0000000-0000-4000-8000-000000000001')=t);
 perform public.messaging_complete_update((c->>'conversationId')::uuid,(c->>'leaseId')::uuid,'2',jsonb_build_object('version',1,'pending',null,'lastTicket',t),jsonb_build_object('text','Received','confirmationNonce',null));
 perform pg_temp.channel_assert(public.messaging_claim_reply((c->>'conversationId')::uuid,'2')->>'status'='claimed');
 perform public.messaging_finish_reply((c->>'conversationId')::uuid,'2','unknown',null);
 perform pg_temp.channel_assert(public.messaging_claim_reply((c->>'conversationId')::uuid,'2')->>'status'='already_attempted');
 c:=public.messaging_claim_update('telegram','testbot',restaurant,'recipient','3',repeat('4',64));
 perform pg_temp.channel_assert(c->'state'->'pending'='null'::jsonb);
 perform pg_temp.channel_assert(public.messaging_submit_order((c->>'conversationId')::uuid,(c->>'leaseId')::uuid,'3','e0000000-0000-4000-8000-000000000001')=t);
 perform pg_temp.channel_assert((select count(*) from public.orders)=2);
 perform pg_temp.channel_assert(not has_function_privilege('anon','public.messaging_claim_update(text,text,uuid,text,text,text)','execute') and not has_function_privilege('authenticated','public.submit_voice_order(uuid,uuid,uuid)','execute'));
 if (select count(*) from pg_temp.channel_checks)<>18 then raise exception 'WRONG_CHANNEL_CHECK_COUNT';end if;
end;
$tests$;
rollback;
select 'jiak_channel_rollback_verified_v1' as verification_marker,18::integer as assertions_passed;
