import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
const actor='a0000000-0000-4000-8000-000000000001', other='a0000000-0000-4000-8000-000000000002', restaurant='b0000000-0000-4000-8000-000000000001';
const menu={id:'c0000000-0000-4000-8000-000000000001',restaurantId:restaurant,version:1,currency:'SGD',name:'Photo test',dishes:[{id:'d0000000-0000-4000-8000-000000000001',name:'Rice',priceCents:450,available:true,modifierGroups:[]}]};
const request={mode:'generate_similar',dishId:menu.dishes[0].id,dishName:'Rice'};
async function rpc(db,name,args){return Object.values((await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})`,args)).rows[0])[0];}
const j=JSON.stringify;
test('photo migration: scoped jobs, durable budgets and immutable reviewed publication',async t=>{
 const db=new PGlite();t.after(()=>db.close());
 await db.exec("create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to public;grant execute on function auth.uid() to public;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);");
 const migration='20260913084500_jiak_simi_dish_photos.sql';
 for(const file of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(file=>file<migration).sort())await db.exec(await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));
 const applied=await readFile(new URL('../supabase/migrations/'+migration,import.meta.url),'utf8');
 assert.equal(applied,await readFile(new URL('../docs/dish-photo-extension.sql',import.meta.url),'utf8'));
 await db.exec(applied);
 await db.exec(`insert into auth.users(id) values('${actor}'),('${other}');insert into public.restaurants(id,name,slug) values('${restaurant}','Photos','photos');insert into public.restaurant_memberships values('${restaurant}','${actor}','owner',true,now());`);
 const details={name:'Photo test',timezone:'Asia/Singapore',weeklyHours:Array.from({length:7},(_,n)=>({weekday:n+1,closed:true,intervals:[]}))};
 await rpc(db,'save_stall_details',[actor,restaurant,0,j(details)]);
 const key=randomUUID();
 const sourceId=randomUUID(), entryId=randomUUID();
 const enhance={...request,mode:'enhance_visible',merchantConfirmedVisible:true,sourceImageId:sourceId,sourceEntryId:entryId};
 await assert.rejects(rpc(db,'reserve_dish_photo_job',[actor,restaurant,randomUUID(),j(enhance),j({sourceImageId:sourceId,objectKey:`outside/sources/${sourceId}`,sha256:'c'.repeat(64),mimeType:'image/jpeg',sizeBytes:1000})]),/INVALID_REQUEST/);
 await assert.rejects(rpc(db,'reserve_dish_photo_job',[actor,restaurant,randomUUID(),j({...enhance,merchantConfirmedVisible:false}),null]),/INVALID_REQUEST/);
 await assert.rejects(rpc(db,'reserve_dish_photo_job',[other,restaurant,key,j(request),null]),/FORBIDDEN/);
 const reserved=await rpc(db,'reserve_dish_photo_job',[actor,restaurant,key,j(request),null]);assert.equal(reserved.dispatchAllowed,true);
 assert.equal((await rpc(db,'read_dish_photo_job',[actor,restaurant,null,key])).jobId,reserved.jobId);
 await assert.rejects(rpc(db,'read_dish_photo_job',[actor,restaurant,reserved.jobId,key]),/INVALID_REQUEST/);
 await assert.rejects(rpc(db,'read_dish_photo_job',[actor,restaurant,null,null]),/INVALID_REQUEST/);
 await assert.rejects(rpc(db,'read_dish_photo_job',[other,restaurant,null,key]),/FORBIDDEN/);
 const retry=await rpc(db,'reserve_dish_photo_job',[actor,restaurant,key,j(request),null]);assert.equal(retry.dispatchAllowed,false);assert.equal(retry.jobId,reserved.jobId);
 await assert.rejects(rpc(db,'reserve_dish_photo_job',[actor,restaurant,key,j({...request,dishName:'Different'}),null]),/IDEMPOTENCY_CONFLICT/);
 await assert.rejects(rpc(db,'read_dish_photo_job',[other,restaurant,reserved.jobId]),/FORBIDDEN/);
 assert.equal((await rpc(db,'read_dish_photo_job',[actor,restaurant,reserved.jobId])).dispatchAllowed,false);
 const result={objectKey:`${restaurant}/candidates/${reserved.jobId}`,sizeBytes:1000,candidate:{id:randomUUID(),dishId:request.dishId,status:'needs_review',mode:'generate_similar',label:'AI-generated illustration',disclosureRequired:true,mimeType:'image/jpeg',imageSha256:'a'.repeat(64),promptSha256:'b'.repeat(64),sourceImageId:null,sourceEntryId:null,sourceImageSha256:null,model:'gpt-image-2.5-sunburst',quality:'low',size:'1024x1024',region:null,createdAt:new Date().toISOString()}};
 await assert.rejects(rpc(db,'finish_dish_photo_job',[actor,restaurant,reserved.jobId,j({...result,candidate:{...result.candidate,disclosureRequired:false}})]),/INVALID_REQUEST/);
 await rpc(db,'finish_dish_photo_job',[actor,restaurant,reserved.jobId,j(result)]);
 await assert.rejects(rpc(db,'finish_dish_photo_job',[actor,restaurant,reserved.jobId,j({...result,sizeBytes:1100})]),/IDEMPOTENCY_CONFLICT/);
 const selections=[{dishId:request.dishId,jobId:reserved.jobId}];
 await assert.rejects(rpc(db,'publish_menu_with_photos',[restaurant,actor,j(menu),1,j([...selections,...selections])]),/INVALID_REQUEST/);
 await assert.rejects(rpc(db,'publish_menu_with_photos',[restaurant,actor,j({...menu,dishes:[{...menu.dishes[0],name:'Renamed'}]}),1,j(selections)]),/STALE_PHOTO/);
 assert.equal((await db.query('select count(*)::int n from private.menu_versions')).rows[0].n,0);
 const published=await rpc(db,'publish_menu_with_photos',[restaurant,actor,j(menu),1,j(selections)]);assert.equal(published.photos.length,1);
 await rpc(db,'publish_menu',[restaurant,actor,j({...menu,version:2}),1]);
 assert.deepEqual(await rpc(db,'read_published_photos',[restaurant,menu.id,1]),published.photos);
 assert.deepEqual(await rpc(db,'read_published_photos',[restaurant,menu.id,2]),[]);
 // Unknown and failed attempts still consume a slot, and key replay never does.
 for(let n=1;n<10;n++)await rpc(db,'reserve_dish_photo_job',[actor,restaurant,randomUUID(),j(request),null]);
 await assert.rejects(rpc(db,'reserve_dish_photo_job',[actor,restaurant,randomUUID(),j(request),null]),/RATE_LIMITED/);
 assert.equal((await rpc(db,'reserve_dish_photo_job',[actor,restaurant,key,j(request),null])).dispatchAllowed,false);
 await db.exec("update private.dish_photo_jobs set created_at=now()-interval '20 minutes'");
 for(let n=0;n<40;n++){await rpc(db,'reserve_dish_photo_job',[actor,restaurant,randomUUID(),j(request),null]);await db.exec("update private.dish_photo_jobs set created_at=now()-interval '20 minutes'");}
 await assert.rejects(rpc(db,'reserve_dish_photo_job',[actor,restaurant,randomUUID(),j(request),null]),/RATE_LIMITED/);
 await db.exec('set role anon');
 await assert.rejects(rpc(db,'read_published_photos',[restaurant,menu.id,1]),/permission denied/);
 await assert.rejects(db.query('select * from private.dish_photo_jobs'),/permission denied/);
});
