-- Scoped fixtures only, rolled back. Safe with existing demo/orders present.
begin;
set local statement_timeout='60s';
set local lock_timeout='5s';
create temporary table web_checks(ok boolean not null);
create function pg_temp.web_assert(p_ok boolean) returns void language plpgsql as $$begin if p_ok is not true then raise exception 'WEB_ASSERTION_FAILED';end if;insert into pg_temp.web_checks values(true);end;$$;
do $tests$
declare actor uuid:='a32f563d-a342-4b3a-a432-41552b32fd98'; restaurant uuid:='b32f563d-a342-4b3a-a432-41552b32fd98'; menu jsonb; cart jsonb; details jsonb; q jsonb; t jsonb; d jsonb; legacy jsonb; n integer;
begin
 if not exists(select 1 from pg_catalog.pg_roles where rolname=current_user and (rolsuper or rolbypassrls)) then raise exception 'PRIVILEGED_VISIBILITY_REQUIRED';end if;
 if exists(select 1 from auth.users where id=actor) or exists(select 1 from public.restaurants where id=restaurant or slug='web-rollback-a32f563d') or exists(select 1 from private.guest_sessions where token_hash=repeat('ab32',16)) then raise exception 'FIXTURE_COLLISION';end if;
 insert into auth.users(id,email) values(actor,'web-rollback-a32f563d@example.invalid');
 insert into public.restaurants(id,name,slug) values(restaurant,'Rollback test','web-rollback-a32f563d');
 insert into public.restaurant_memberships(restaurant_id,user_id,role) values(restaurant,actor,'owner');
 select jsonb_build_object('name','Reviewed stall','timezone','Asia/Singapore','weeklyHours',jsonb_agg(jsonb_build_object('weekday',day,'closed',false,'intervals',jsonb_build_array(jsonb_build_object('opens','09:00','closes','20:00','closesNextDay',false))))) into details from generate_series(1,7) day;
 perform pg_temp.web_assert(public.save_stall_details(actor,restaurant,0,details)->'details'->>'version'='1');
 menu:=jsonb_build_object('id','c32f563d-a342-4b3a-a432-41552b32fd98','restaurantId',restaurant,'version',1,'currency','SGD','name','Joint rollback menu','dishes','[{"id":"d32f563d-a342-4b3a-a432-41552b32fd98","name":"Char Siew Rice","priceCents":450,"available":true,"modifierGroups":[]},{"id":"d32f563d-a342-4b3a-a432-41552b32fd99","name":"Braised Pork Knuckle Rice","priceCents":500,"available":true,"modifierGroups":[]}]'::jsonb);
 perform public.publish_menu(restaurant,actor,menu,1);
 perform public.create_guest_session(restaurant,repeat('ab32',16));
 cart:=jsonb_build_object('restaurantId',restaurant,'menuId',menu->>'id','menuVersion',1,'fulfillmentType','takeaway','lines','[{"dishId":"d32f563d-a342-4b3a-a432-41552b32fd98","quantity":2,"optionIds":[]},{"dishId":"d32f563d-a342-4b3a-a432-41552b32fd99","quantity":1,"optionIds":[]}]'::jsonb);
 q:=public.quote_cart(repeat('ab32',16),cart);
 perform pg_temp.web_assert(q->>'totalCents'='1400' and q->>'fulfillmentType'='takeaway');
 perform pg_temp.web_assert(public.quote_cart(repeat('ab32',16),jsonb_set(cart,'{fulfillmentType}','"dine_in"'))->>'totalCents'='1400');
 begin perform public.quote_cart(repeat('ab32',16),cart-'fulfillmentType');raise exception 'EXPECTED_INVALID_CART';exception when raise_exception then if sqlerrm<>'INVALID_CART' then raise;end if;end;
 perform pg_temp.web_assert(true);
 t:=public.submit_order(repeat('ab32',16),cart,1400,'web','e32f563d-a342-4b3a-a432-41552b32fd98');
 perform pg_temp.web_assert(t->>'status'='received' and t->>'statusVersion'='1' and t->'completedAt'='null'::jsonb and t->>'paymentStatus'='unpaid');
 d:=public.complete_kitchen_order(actor,restaurant,(t->>'id')::uuid,1,'f32f563d-a342-4b3a-a432-41552b32fd98');
 perform pg_temp.web_assert(d->>'status'='done' and d->>'statusVersion'='2' and d->>'completedAt' is not null and d->>'paymentStatus'='unpaid');
 perform pg_temp.web_assert(public.complete_kitchen_order(actor,restaurant,(t->>'id')::uuid,1,'f32f563d-a342-4b3a-a432-41552b32fd98')=d);
 begin perform public.complete_kitchen_order(actor,restaurant,(t->>'id')::uuid,1,'f32f563d-a342-4b3a-a432-41552b32fd99');raise exception 'EXPECTED_STALE';exception when raise_exception then if sqlerrm<>'STALE_STATUS' then raise;end if;end;
 perform pg_temp.web_assert(true);
 perform pg_temp.web_assert(public.read_kitchen_orders(restaurant,actor)->'counts'='{"received":0,"done":1,"total":1}'::jsonb);
 perform pg_temp.web_assert(public.submit_order(repeat('ab32',16),cart,1400,'web','e32f563d-a342-4b3a-a432-41552b32fd98')=t);
 perform pg_temp.web_assert((select status='received' and payment_status='unpaid' and total_cents=1400 from public.orders where id=(t->>'id')::uuid));
 legacy:=private.immutable_ticket_response((t-'statusVersion'-'completedAt') #- '{cart,fulfillmentType}');
 perform pg_temp.web_assert(legacy->'cart'->'fulfillmentType'='null'::jsonb and legacy->>'statusVersion'='1');
 perform public.save_stall_details(actor,restaurant,1,jsonb_set(details,'{name}','"New draft name"'));
 perform pg_temp.web_assert(public.read_published_stall(restaurant)->'details'->>'name'='Reviewed stall');
 begin perform public.publish_menu(restaurant,actor,jsonb_set(menu,'{version}','2'),1);raise exception 'EXPECTED_STALE_DETAILS';exception when raise_exception then if sqlerrm<>'STALE_STALL_DETAILS' then raise;end if;end;
 perform pg_temp.web_assert(true);
 perform public.publish_menu(restaurant,actor,jsonb_set(menu,'{version}','2'),2);
 perform pg_temp.web_assert(public.read_published_stall(restaurant)->'details'->>'name'='New draft name');
 perform pg_temp.web_assert(not has_function_privilege('anon','public.complete_kitchen_order(uuid,uuid,uuid,integer,uuid)','execute') and not has_function_privilege('authenticated','public.save_stall_details(uuid,uuid,integer,jsonb)','execute'));
 if (select count(*) from pg_temp.web_checks)<>16 then raise exception 'WRONG_WEB_CHECK_COUNT';end if;
end;
$tests$;
rollback;
select 'jiak_web_rollback_verified_v1' as verification_marker,16::integer as assertions_passed;
